---
label: Project
hide_body: false
fields:
- type: text
  name: uid
  label: uid
- type: text
  name: title
  label: title
- type: text
  name: color
  label: color
- type: list
  name: tags
  label: tags
- type: field_group
  name: images
  label: images
- type: field_group
  name: links
  label: links
