---
label: Project
hide_body: false
fields:
- type: text
  name: uid
  label: uid
- type: text
  name: title
  label: title
- type: text
  name: color
  label: color
- name: color2
  type: color
  config:
    required: false
    color_format: Hex
  label: Color
- type: list
  name: tags
  label: tags
- type: field_group
  name: links
  label: links
- name: images2
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: title
    type: text
    config:
      required: false
    label: Title
  config:
    min: 
    max: 
    labelField: 
  label: Images
