---
label: Project
hide_body: false
fields:
- type: text
  name: uid
  label: uid
- type: text
  name: title
  label: title
- type: text
  name: color
  label: color
- type: list
  name: tags
  label: tags
- name: images2
  type: image_gallery
  config: {}
  label: images2
- type: field_group
  name: links
  label: links
