# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: '_posts/'
    fields:
      - { name: Title }
